const channels=[['التحول الرقمي',5],['المشروعات الاستراتيجية',2],['الإعلانات',0],['الفريق التنفيذي',0],['عام',0]];
const people=[['سارة أحمد','س'],['محمد علي','م'],['ريم خالد','ر'],['فريق الدعم','د']];
const initialMessages=[
 {name:'سارة أحمد',avatar:'س',time:'09:42',text:'صباح الخير جميعاً، تم الانتهاء من مراجعة خارطة الطريق التقنية. أضفت الملاحظات النهائية ومصفوفة الأولويات للربع القادم.'},
 {name:'محمد علي',avatar:'م',time:'09:48',text:'ممتاز. بيئة الاتصالات الداخلية مستقرة الآن، واختبارات التشفير والنسخ الاحتياطي اجتازت معايير القبول.'},
 {name:'ريم خالد',avatar:'ر',time:'10:05',text:'أرفقت النسخة المحدثة من وثيقة الحوكمة وسياسات الاحتفاظ بالبيانات.',file:'سياسة الحوكمة والاحتفاظ.pdf · 2.4 MB'},
 {name:'سارة أحمد',avatar:'س',time:'10:11',text:'نلتقي الساعة 11:30 لمراجعة تجربة الموظف قبل الإطلاق التجريبي. الدعوة موجودة في تقويم الفريق.'}
];
const files=[['▤','سياسة حوكمة الاتصالات','PDF · 2.4 MB'],['▧','خارطة الطريق التقنية','XLSX · 840 KB'],['◫','عرض الإطلاق المؤسسي','PPTX · 6.1 MB'],['▱','دليل الهوية الخاصة','ZIP · 18 MB'],['▤','تقرير اختبار الأمان','PDF · 1.7 MB'],['▧','سجل الأصول والخوادم','XLSX · 910 KB']];
const loginScreen=document.querySelector('#loginScreen'),appShell=document.querySelector('#appShell'),loginForm=document.querySelector('#loginForm');
loginForm.addEventListener('submit',e=>{e.preventDefault();const btn=loginForm.querySelector('.login-submit');btn.querySelector('span').textContent='جارٍ التحقق الآمن…';btn.disabled=true;setTimeout(()=>{loginScreen.classList.add('exit');setTimeout(()=>{loginScreen.hidden=true;appShell.classList.remove('locked');document.body.style.overflow='hidden';toast('مرحباً بك في مساحة وَصْل السيادية')},620)},700)});
document.querySelector('#togglePassword').addEventListener('click',()=>{const p=document.querySelector('#password');p.type=p.type==='password'?'text':'password'});
document.querySelector('#logoutButton').addEventListener('click',()=>{appShell.classList.add('locked');loginScreen.hidden=false;loginScreen.classList.remove('exit');loginForm.querySelector('.login-submit span').textContent='الدخول إلى وَصْل';loginForm.querySelector('.login-submit').disabled=false});
const channelList=document.querySelector('#channelList'); channels.forEach(([name,count],i)=>{const b=document.createElement('button');b.className='channel '+(i===0?'active':'');b.innerHTML=`<span>#</span><span>${name}</span>${count?`<b>${count}</b>`:''}`;b.onclick=()=>{document.querySelectorAll('.channel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#channelName').textContent=name;document.querySelector('#channelDesc').textContent=i===0?'تنسيق البرامج والمشروعات الرقمية':'مساحة عمل الفريق ومشاركة المستجدات'};channelList.appendChild(b)});
const peopleList=document.querySelector('#peopleList');people.forEach(([name,a])=>{const b=document.createElement('button');b.className='person';b.innerHTML=`<span class="avatar">${a}</span><span>${name}</span><i></i>`;peopleList.appendChild(b)});
const messageBox=document.querySelector('#messages');function addMessage(m){const el=document.createElement('article');el.className='message';el.innerHTML=`<span class="avatar ${m.avatar==='س'?'green':'blue'}">${m.avatar}</span><div class="message-head"><strong>${m.name}</strong><time>${m.time}</time></div><div><p>${m.text}</p>${m.file?`<div class="attachment"><span class="filetype">PDF</span><div><strong>${m.file.split(' · ')[0]}</strong><br><span>${m.file.split(' · ')[1]}</span></div></div>`:''}</div>`;messageBox.appendChild(el)}initialMessages.forEach(addMessage);
const composer=document.querySelector('#composer'),input=document.querySelector('#messageInput');composer.onsubmit=e=>{e.preventDefault();const v=input.value.trim();if(!v)return;addMessage({name:'لؤي أحمد',avatar:'ل',time:new Date().toLocaleTimeString('ar',{hour:'2-digit',minute:'2-digit'}),text:v});input.value='';messageBox.scrollTop=messageBox.scrollHeight;toast('تم إرسال الرسالة داخل القناة')};
files.forEach(([icon,name,meta])=>{document.querySelector('#fileGrid').insertAdjacentHTML('beforeend',`<article class="file-card"><div class="file-icon">${icon}</div><b>${name}</b><span>${meta}</span></article>`)});
document.querySelectorAll('.rail-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.rail-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector(`#${b.dataset.view}View`).classList.add('active')});
const modal=document.querySelector('#meetingModal');['videoCall','startMeeting','heroMeeting'].forEach(id=>document.querySelector('#'+id)?.addEventListener('click',()=>{modal.classList.add('show');modal.setAttribute('aria-hidden','false')}));document.querySelector('#closeModal').onclick=()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true')};modal.onclick=e=>{if(e.target===modal)document.querySelector('#closeModal').click()};
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelector('#newMessage').onclick=()=>{input.focus();toast('ابدأ بكتابة رسالتك')};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('#search').focus()}});
